
  name: JavaScript action
  on: 
    push: 
      branches: [main]
    workflow_dispatch:

  jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: aroyan/custom-action@main
            with: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
